language: node_js
node_js:
- "7"
branches:
  only:
    - master
cache:
  directories:
    - "node_modules"
install:
  - npm i -g codecov
  - npm install
script:
  - npm run coverage && codecov -t $CODE_COV_TOKEN
